"""
Value objects for the Health Insight Agent domain.

This module contains immutable value objects that represent
concepts without identity in the health analysis domain.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum
from uuid import UUID, uuid4

from .entities import RiskLevel, SeverityLevel


class InsightType(Enum):
    """Types of health insights that can be generated."""
    GENERAL_HEALTH = "general_health"
    RISK_FACTOR = "risk_factor"
    TREND_ANALYSIS = "trend_analysis"
    SYMPTOM_CORRELATION = "symptom_correlation"
    MEDICATION_INTERACTION = "medication_interaction"
    LIFESTYLE_RECOMMENDATION = "lifestyle_recommendation"


class RecommendationType(Enum):
    """Types of health recommendations."""
    LIFESTYLE_CHANGE = "lifestyle_change"
    MEDICAL_CONSULTATION = "medical_consultation"
    MEDICATION_ADJUSTMENT = "medication_adjustment"
    DIAGNOSTIC_TEST = "diagnostic_test"
    MONITORING = "monitoring"
    EMERGENCY_CARE = "emergency_care"


class RecommendationPriority(Enum):
    """Priority levels for recommendations."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


@dataclass(frozen=True)
class HealthInsight:
    """Represents a single health insight generated by AI analysis."""
    
    insight_type: InsightType
    title: str
    description: str
    confidence_score: float  # 0.0 to 1.0
    supporting_data: Dict[str, Any] = field(default_factory=dict)
    generated_at: datetime = field(default_factory=datetime.utcnow)
    
    def __post_init__(self):
        """Validate health insight data."""
        if not self.title or not self.title.strip():
            raise ValueError("Insight title cannot be empty")
        
        if not self.description or not self.description.strip():
            raise ValueError("Insight description cannot be empty")
        
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
    
    @property
    def is_high_confidence(self) -> bool:
        """Check if this insight has high confidence (>= 0.8)."""
        return self.confidence_score >= 0.8
    
    @property
    def is_actionable(self) -> bool:
        """Check if this insight suggests actionable items."""
        actionable_types = {
            InsightType.RISK_FACTOR,
            InsightType.MEDICATION_INTERACTION,
            InsightType.LIFESTYLE_RECOMMENDATION
        }
        return self.insight_type in actionable_types


@dataclass(frozen=True)
class RiskFactor:
    """Represents a specific health risk factor."""
    
    name: str
    risk_level: RiskLevel
    probability: float  # 0.0 to 1.0
    contributing_factors: List[str] = field(default_factory=list)
    mitigation_strategies: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        """Validate risk factor data."""
        if not self.name or not self.name.strip():
            raise ValueError("Risk factor name cannot be empty")
        
        if not (0.0 <= self.probability <= 1.0):
            raise ValueError("Risk probability must be between 0.0 and 1.0")


@dataclass(frozen=True)
class RiskAssessment:
    """Represents a comprehensive risk assessment for a patient."""
    
    overall_risk_level: RiskLevel
    risk_factors: List[RiskFactor] = field(default_factory=list)
    assessment_summary: str = ""
    confidence_score: float = 0.0  # 0.0 to 1.0
    assessed_at: datetime = field(default_factory=datetime.utcnow)
    
    def __post_init__(self):
        """Validate risk assessment data."""
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
    
    @property
    def high_risk_factors(self) -> List[RiskFactor]:
        """Get risk factors with high or very high risk levels."""
        return [
            factor for factor in self.risk_factors 
            if factor.risk_level in [RiskLevel.HIGH, RiskLevel.VERY_HIGH]
        ]
    
    @property
    def requires_immediate_attention(self) -> bool:
        """Check if the assessment indicates need for immediate attention."""
        return (
            self.overall_risk_level == RiskLevel.VERY_HIGH or
            len(self.high_risk_factors) >= 2
        )


@dataclass(frozen=True)
class Recommendation:
    """Represents a health recommendation for a patient."""
    
    recommendation_type: RecommendationType
    priority: RecommendationPriority
    title: str
    description: str
    rationale: str
    expected_outcome: Optional[str] = None
    timeframe: Optional[str] = None  # e.g., "within 24 hours", "in 2 weeks"
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    def __post_init__(self):
        """Validate recommendation data."""
        if not self.title or not self.title.strip():
            raise ValueError("Recommendation title cannot be empty")
        
        if not self.description or not self.description.strip():
            raise ValueError("Recommendation description cannot be empty")
        
        if not self.rationale or not self.rationale.strip():
            raise ValueError("Recommendation rationale cannot be empty")
    
    @property
    def is_urgent(self) -> bool:
        """Check if this recommendation is urgent."""
        return self.priority == RecommendationPriority.URGENT
    
    @property
    def requires_medical_attention(self) -> bool:
        """Check if this recommendation requires medical professional involvement."""
        medical_types = {
            RecommendationType.MEDICAL_CONSULTATION,
            RecommendationType.MEDICATION_ADJUSTMENT,
            RecommendationType.DIAGNOSTIC_TEST,
            RecommendationType.EMERGENCY_CARE
        }
        return self.recommendation_type in medical_types


@dataclass
class InsightReport:
    """Represents a comprehensive insight report for a patient."""
    
    report_id: UUID = field(default_factory=uuid4)
    patient_id: str = ""
    insights: List[HealthInsight] = field(default_factory=list)
    risk_assessment: Optional[RiskAssessment] = None
    recommendations: List[Recommendation] = field(default_factory=list)
    confidence_score: float = 0.0  # Overall confidence in the report
    generated_at: datetime = field(default_factory=datetime.utcnow)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate insight report data."""
        if not self.patient_id or not self.patient_id.strip():
            raise ValueError("Patient ID cannot be empty")
        
        if not (0.0 <= self.confidence_score <= 1.0):
            raise ValueError("Confidence score must be between 0.0 and 1.0")
    
    @property
    def high_confidence_insights(self) -> List[HealthInsight]:
        """Get insights with high confidence scores."""
        return [insight for insight in self.insights if insight.is_high_confidence]
    
    @property
    def urgent_recommendations(self) -> List[Recommendation]:
        """Get urgent recommendations from the report."""
        return [rec for rec in self.recommendations if rec.is_urgent]
    
    @property
    def actionable_insights(self) -> List[HealthInsight]:
        """Get insights that suggest actionable items."""
        return [insight for insight in self.insights if insight.is_actionable]
    
    def add_insight(self, insight: HealthInsight) -> None:
        """Add a new insight to the report."""
        if insight not in self.insights:
            self.insights.append(insight)
    
    def add_recommendation(self, recommendation: Recommendation) -> None:
        """Add a new recommendation to the report."""
        if recommendation not in self.recommendations:
            self.recommendations.append(recommendation)
    
    def get_summary(self) -> Dict[str, Any]:
        """Get a summary of the insight report."""
        return {
            "report_id": str(self.report_id),
            "patient_id": self.patient_id,
            "total_insights": len(self.insights),
            "high_confidence_insights": len(self.high_confidence_insights),
            "total_recommendations": len(self.recommendations),
            "urgent_recommendations": len(self.urgent_recommendations),
            "overall_risk_level": self.risk_assessment.overall_risk_level.value if self.risk_assessment else None,
            "confidence_score": self.confidence_score,
            "generated_at": self.generated_at.isoformat()
        }